import { useMemo } from "react";
import type { AppData } from "../appData";
import type { InspectorSelection } from "../types";
import type { ResearchState } from "../lib/urlState";
import { EvidenceBadge, SectionHeading, formatNumber } from "./shared";
import { ResearchChart } from "../components/ResearchChart";

export function InstitutionsView({ data, state, onSelect }: { data: AppData; state: ResearchState; onSelect: (selection: InspectorSelection) => void }) {
  const visibleObservations = data.metricObservations.filter((observation) => observation.periodEnd >= state.from && (observation.periodStart ?? observation.periodEnd) <= state.to);
  const camps = data.camps.filter((camp) => (!state.camps.length || state.camps.includes(camp.id)) && visibleObservations.some((observation) => observation.campId === camp.id && data.metricDefinitions.find((definition) => definition.id === observation.metricId)?.domain === "institutional"));
  const definitions = data.metricDefinitions.filter((definition) => definition.domain === "institutional" && (!state.measures.length || state.measures.includes(definition.id)));
  const observations = new Map(visibleObservations.map((observation) => [`${observation.campId}:${observation.metricId}`, observation]));
  const chartDefinitions = definitions.filter((definition) => ["published_members", "democratic_leadership_offices", "standing_committee_ranking_members"].includes(definition.id));
  const chartOption = useMemo(() => ({ animation: false, color: camps.map((camp) => camp.color), tooltip: { trigger: "axis", axisPointer: { type: "shadow" } }, legend: { top: 0, textStyle: { fontSize: 10 } }, grid: { left: 180, right: 20, top: 45, bottom: 28 }, xAxis: { type: "value", splitLine: { lineStyle: { color: "#e7e9ec" } } }, yAxis: { type: "category", data: chartDefinitions.map((definition) => definition.label), axisLabel: { width: 165, overflow: "truncate", fontSize: 9 } }, series: camps.map((camp) => ({ name: camp.shortName, type: "bar", barMaxWidth: 14, data: chartDefinitions.map((definition) => observations.get(`${camp.id}:${definition.id}`)?.value ?? null) })) }), [camps, chartDefinitions, observations]);
  const roles = data.relationships.filter((relationship) => (relationship.type === "caucus_officer" || relationship.type.includes("member")) && (state.evidence === "all" || relationship.evidenceGrade !== "D") && (!relationship.cycle || state.cycles.includes(relationship.cycle)) && (relationship.validFrom ?? "0000-01-01") <= state.to && (relationship.validTo ?? "9999-12-31") > state.from && (!state.organization || relationship.organizationId === state.organization));
  const people = new Map(data.people.map((person) => [person.id, person]));
  const organizations = new Map(data.organizations.map((organization) => [organization.id, organization]));

  return <div className="view-stack"><section className="research-card chart-card"><SectionHeading eyebrow="INSTITUTIONAL POWER" title="Scale, leadership, and committee reach" description="Formal caucus memberships overlap. Counts use full attribution and must not be summed into a party-wide share." /><ResearchChart option={chartOption} height={380} />{(state.chamber !== "all" || state.states.length > 0) && <p className="scope-warning">Migrated caucus aggregates do not carry a member-level chamber or geography denominator. The temporal relation list below applies the defensible filters; the chart does not.</p>}</section>
    <section className="research-card"><SectionHeading eyebrow="OBSERVATION MATRIX" title="Institutional evidence" description="Every measure retains its eligible universe, fixed transform, missing-data rule, and field-level caveat." /><div className="matrix-wrap"><table className="evidence-matrix"><thead><tr><th>Measure</th>{camps.map((camp) => <th key={camp.id}>{camp.shortName}</th>)}<th>Coverage rule</th></tr></thead><tbody>{definitions.map((definition) => <tr key={definition.id}><th><strong>{definition.label}</strong><small>{definition.description}</small></th>{camps.map((camp) => { const observation = observations.get(`${camp.id}:${definition.id}`); return <td key={camp.id}><button type="button" disabled={!observation} onClick={() => observation && onSelect({ kind: "institutional observation", id: observation.id, title: `${definition.label} · ${camp.shortName}`, subtitle: definition.caveat, record: { ...observation, eligibleUniverse: definition.eligibleUniverse, missingDataPolicy: definition.missingDataPolicy }, sourceIds: observation.sourceIds })}>{observation ? <span className="metric-value"><strong>{formatNumber(observation.value, definition.format)}</strong><EvidenceBadge grade={observation.evidenceGrade} /></span> : "—"}</button></td>; })}<td>{Math.round(definition.coverageThreshold * 100)}%<small>min n {definition.minimumSample}</small></td></tr>)}</tbody></table></div></section>
    <div className="institution-columns"><section className="research-card"><SectionHeading eyebrow="TEMPORAL FACTS" title="Reviewed membership and office spells" description="The starter relation set powers taxonomy regression checks while historical roster reconstruction remains in the review queue." />{roles.map((relationship) => <button type="button" className="relation-row" key={relationship.id} onClick={() => onSelect({ kind: "organization relationship", id: relationship.id, title: `${people.get(relationship.personId)?.name} · ${organizations.get(relationship.organizationId)?.shortName}`, subtitle: relationship.type.replaceAll("_", " "), record: relationship as unknown as Record<string, unknown>, evidenceIds: [`evidence-${relationship.id}`] })}><span className="grade grade-a">{relationship.evidenceGrade}</span><div><strong>{people.get(relationship.personId)?.name}</strong><p>{relationship.type.replaceAll("_", " ")} · {organizations.get(relationship.organizationId)?.name}</p></div><time>{relationship.validFrom ?? `observed ${relationship.observedAt.slice(0, 10)}`}</time></button>)}</section>
    <aside className="research-card staged-module"><SectionHeading eyebrow="STAGED CONTEXT MODULE" title="Roll-call dimensions" description="Voteview and official House/Senate vote files are identified as the next reproducible feed." /><div className="module-status"><span>Not redistributed in this release</span><strong>Licence and longitudinal join review</strong><p>The workbench does not silently substitute current-vote snapshots for a complete 2018–present roll-call series. Vote-based dimensions remain unscored until identity joins, chamber-specific windows, and redistribution terms pass review.</p><a href="https://voteview.com/data" target="_blank" rel="noreferrer">Inspect Voteview’s published data page ↗</a></div><div className="context-list"><span>Planned disclosed dimensions</span><p>Nokken–Poole within-Congress percentile</p><p>Democratic-majority alignment</p><p>Attendance and contested-roll-call denominator</p><p>Cosponsorship centrality from Congress.gov</p></div></aside></div>
  </div>;
}
