import { useMemo, useState } from "react";
import type { AppData } from "../appData";
import type { InspectorSelection } from "../types";
import type { ResearchState } from "../lib/urlState";
import { CoveragePill, SectionHeading, formatNumber } from "./shared";
import { ResearchChart } from "../components/ResearchChart";

export function ModelView({ data, state, onState, onSelect }: { data: AppData; state: ResearchState; onState: (patch: Partial<ResearchState>) => void; onSelect: (selection: InspectorSelection) => void }) {
  const defaultWeights = Object.fromEntries(data.modelBundle.model.domains.map((domain) => [domain.id, Math.round(domain.weight * 100)]));
  const weights = { ...defaultWeights, ...state.modelWeights };
  const [selectedCampId, setSelectedCampId] = useState("cpc_aligned");
  const campMap = new Map(data.camps.map((camp) => [camp.id, camp]));
  const weightedScores = useMemo(() => data.modelBundle.scores.filter((score) => !state.camps.length || state.camps.includes(score.campId)).map((score) => {
    if (!score.sufficient) return { ...score, adjustedScore: null, adjusted80: [null, null] as [number | null, number | null], adjusted95: [null, null] as [number | null, number | null] };
    const total = score.domainScores.reduce((sum, domain) => sum + (weights[domain.id] ?? 0), 0);
    if (!total) return { ...score, adjustedScore: null, adjusted80: [null, null] as [number | null, number | null], adjusted95: [null, null] as [number | null, number | null] };
    const adjustedScore = score.domainScores.reduce((sum, domain) => sum + domain.score! * (weights[domain.id] ?? 0), 0) / total;
    const adjusted80 = [0, 1].map((index) => score.domainScores.reduce((sum, domain) => sum + domain.interval80[index]! * (weights[domain.id] ?? 0), 0) / total) as [number, number];
    const adjusted95 = [0, 1].map((index) => score.domainScores.reduce((sum, domain) => sum + domain.interval95[index]! * (weights[domain.id] ?? 0), 0) / total) as [number, number];
    return { ...score, adjustedScore, adjusted80, adjusted95 };
  }).sort((left, right) => (right.adjustedScore ?? -1) - (left.adjustedScore ?? -1)), [data.modelBundle.scores, weights, state.camps]);
  const selected = weightedScores.find((score) => score.campId === selectedCampId) ?? weightedScores[0] ?? data.modelBundle.scores[0];
  const metricMap = new Map(data.metricDefinitions.map((definition) => [definition.id, definition]));
  const sensitivityValues = selected.leaveOneMetricOut.filter((item) => item.score !== null).map((item) => item.score!);
  const weightValues = selected.weightSensitivity.filter((item) => item.score !== null).map((item) => item.score!);
  const chartOption = { animation: false, color: weightedScores.map((score) => campMap.get(score.campId)?.color), tooltip: { trigger: "axis", axisPointer: { type: "shadow" } }, grid: { left: 145, right: 35, top: 28, bottom: 35 }, xAxis: { type: "value", min: 0, max: 100, splitLine: { lineStyle: { color: "#e6e9ed" } } }, yAxis: { type: "category", inverse: true, data: weightedScores.map((score) => campMap.get(score.campId)?.shortName), axisLabel: { fontSize: 10 } }, series: [{ type: "bar", barWidth: 22, data: weightedScores.map((score) => ({ value: score.adjustedScore, itemStyle: { color: campMap.get(score.campId)?.color } })), label: { show: true, position: "right", formatter: (params: { value?: number | null }) => params.value === null || params.value === undefined ? "insufficient" : params.value.toFixed(1), fontSize: 10 } }] };

  const modelScopeChanged = state.from !== "2018-01-01" || state.to < data.manifest.reviewedThrough || state.chamber !== "all" || state.states.length > 0 || state.cycles.length < 5;
  return <div className="view-stack"><section className="research-card model-intro"><SectionHeading eyebrow="SECONDARY ANALYTIC LENS" title="balanced-core-v1" description="The Model Lab is deliberately secondary to the raw evidence matrix. Fixed anchors replace within-visible-camp min–max scaling." /><div className="method-chips"><span>Target reference: {data.modelBundle.model.referencePeriod}</span><span>Domain gate: {Math.round(data.modelBundle.model.coverageThreshold * 100)}%</span><span>Attribution: {state.credit.replaceAll("_", " ")}</span><span>Jeffreys 80% + 95% intervals</span></div>{!data.modelBundle.referenceDistribution.acceptanceEligible && <p className="scope-warning"><strong>Provisional reference:</strong> {data.modelBundle.referenceDistribution.method}</p>}{modelScopeChanged && <p className="scope-warning">This released model is locked to its documented federal 2018–present scope. Narrower date, chamber, cycle, or geography filters do not silently rescale its scores.</p>}</section>
    <div className="model-grid"><aside className="research-card model-controls"><SectionHeading eyebrow="WEIGHTS" title="What counts as power?" description="Weights are encoded in the shareable URL for this model view; raw observations remain immutable." />{data.modelBundle.model.domains.map((domain) => <label className="weight-control" key={domain.id}><span><strong>{domain.label}</strong><output>{weights[domain.id]}%</output></span><input type="range" min="0" max="50" step="1" value={weights[domain.id]} onChange={(event) => onState({ modelWeights: { ...state.modelWeights, [domain.id]: Number(event.target.value) } })} /><small>{domain.measures.length} configured measure{domain.measures.length === 1 ? "" : "s"}</small></label>)}<button type="button" className="quiet-button full" onClick={() => onState({ modelWeights: {} })}>Reset balanced weights</button><p className="formula-note">Overall scores require every domain. Changing weights never fills a missing domain or weakens the 70% gate.</p></aside>
    <section className="research-card chart-card"><SectionHeading eyebrow="RESULTS" title="Coverage-gated comparison" description="Error intervals reflect rate uncertainty where available; deterministic aggregate counts retain point values." /><ResearchChart option={chartOption} height={410} /><div className="model-result-list">{weightedScores.map((score, index) => <button type="button" key={score.campId} className={selectedCampId === score.campId ? "selected" : ""} onClick={() => { setSelectedCampId(score.campId); onSelect({ kind: "model result", id: score.campId, title: campMap.get(score.campId)!.name, subtitle: score.adjustedScore === null ? "Insufficient coverage" : `Adjusted rank ${index + 1}`, record: score as unknown as Record<string, unknown> }); }}><span style={{ background: campMap.get(score.campId)?.color }}></span><strong>{campMap.get(score.campId)?.shortName}</strong><b>{score.adjustedScore === null ? "Insufficient" : score.adjustedScore.toFixed(1)}</b><small>{score.adjustedScore === null ? "missing required domains" : `80% ${formatNumber(score.adjusted80[0])}–${formatNumber(score.adjusted80[1])} · 95% ${formatNumber(score.adjusted95[0])}–${formatNumber(score.adjusted95[1])}`}</small></button>)}</div></section></div>
    <section className="research-card"><SectionHeading eyebrow="INPUT AUDIT" title={`${campMap.get(selected.campId)?.name} model trace`} description="Raw numerators, denominators, fixed-normalized inputs, coverage, and measure weights are all inspectable." /><div className="model-domain-grid">{selected.domainScores.map((domain) => <article key={domain.id}><header><div><strong>{domain.label}</strong><small>{Math.round((weights[domain.id] ?? 0))}% current weight</small></div>{domain.sufficient ? <CoveragePill value={domain.coverage} /> : <span className="warning-label">Insufficient</span>}</header><b>{domain.score === null ? "—" : domain.score.toFixed(1)}</b>{domain.inputs.map((input) => <button type="button" key={input.metricId} onClick={() => { const definition = metricMap.get(input.metricId)!; const observation = data.metricObservations.find((item) => item.campId === selected.campId && item.metricId === input.metricId)!; onSelect({ kind: "model input", id: observation.id, title: `${definition.label} · ${campMap.get(selected.campId)?.shortName}`, subtitle: definition.caveat, record: { ...input, rawObservation: observation, definition }, sourceIds: observation.sourceIds }); }}><span>{metricMap.get(input.metricId)?.label}</span><strong>{formatNumber(input.raw, metricMap.get(input.metricId)?.format)}</strong><small>normalized {input.score.toFixed(1)} · {Math.round(input.weight * 100)}%</small></button>)}</article>)}</div></section>
    <div className="sensitivity-grid"><section className="research-card"><SectionHeading eyebrow="ROBUSTNESS" title="Leave one metric out" description="Range across reproducible leave-one-out runs; insufficient runs remain excluded from the numeric range." /><div className="range-summary"><strong>{sensitivityValues.length ? Math.min(...sensitivityValues).toFixed(1) : "—"}</strong><span>to</span><strong>{sensitivityValues.length ? Math.max(...sensitivityValues).toFixed(1) : "—"}</strong></div>{selected.leaveOneMetricOut.map((item) => <div className="sensitivity-row" key={item.metricId}><span>{metricMap.get(item.metricId)?.label}</span><strong>{item.score === null ? "insufficient" : item.score.toFixed(1)}</strong></div>)}</section><section className="research-card"><SectionHeading eyebrow="ROBUSTNESS" title="±20% domain-weight tests" description="Each domain is perturbed separately and all weights are renormalized." /><div className="range-summary"><strong>{weightValues.length ? Math.min(...weightValues).toFixed(1) : "—"}</strong><span>to</span><strong>{weightValues.length ? Math.max(...weightValues).toFixed(1) : "—"}</strong></div>{selected.weightSensitivity.map((item) => <div className="sensitivity-row" key={`${item.domainId}-${item.multiplier}`}><span>{item.domainId} × {item.multiplier}</span><strong>{item.score === null ? "insufficient" : item.score.toFixed(1)}</strong></div>)}</section><section className="research-card"><SectionHeading eyebrow="ROBUSTNESS" title="Attribution-mode sensitivity" description="Overlapping camp totals are recalculated under full, confidence-weighted, and split-credit interpretations where granular inputs permit it." />{selected.attributionSensitivity.map((item) => <div className="sensitivity-row" key={item.mode}><span>{item.mode.replaceAll("_", " ")}</span><strong>{item.score === null ? "insufficient" : item.score.toFixed(1)}</strong><small>{item.note}</small></div>)}</section></div>
  </div>;
}
